source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
inhibit_all_warnings!

target 'Example' do
#    pod 'R.swift', '~> 2.0'
#    pod 'RxSwift', '~> 2.0'
    pod 'RxCocoa', '~> 2.0'
#    
    #pod 'SegueKit', :path => '../'
    #pod 'SegueKit/R.swift', :path => '../'
    #pod 'SegueKit/RxSwift', :path => '../'
    pod 'SegueKit/Extension', :path => '../'
end

target 'Example_Tests' do
    
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '2.3'
            config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '10.10'
        end
    end
end
