source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
inhibit_all_warnings!

target 'Example' do
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'RxOptional'
    pod 'RxDataSources'
    pod 'R.swift'
    #pod 'SegueKit', :path => '../'
    #pod 'SegueKit/R.swift', :path => '../'
    #pod 'SegueKit/RxSwift', :path => '../'
    pod 'SegueKit/Extension', :path => '../'
end

target 'Example_Tests' do
    
end
