source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
inhibit_all_warnings!

target 'RSegueKit-iOS' do
    # pod 'RxSwift'
    pod 'R.swift'
end

target 'ExtSegueKit-iOS' do
    pod 'R.swift'
end
